use cdms;

CREATE TABLE Age_Group(
    ageGroupId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ageGroupName VARCHAR(50)
);

CREATE TABLE Variety(
    varietyId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    varietyName VARCHAR(50),
    ageGroupId INT,
    CONSTRAINT FOREIGN KEY(ageGroupId) REFERENCES Age_Group(ageGroupId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE Years(
    yearId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    yearRef VARCHAR(20)
);

CREATE TABLE Seasons(
    seasonId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    seasonName VARCHAR(20)
);

CREATE TABLE Months(
    monthId INT PRIMARY KEY AUTO_INCREMENT,
    monthName VARCHAR(20),
    seasonId INT,
    CONSTRAINT FOREIGN KEY(seasonId) REFERENCES Seasons(seasonId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE MajorPaddy(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    yearId INT,
    monthId INT,
    varietyId INT,
    monthlyProgress FLOAT,
    CONSTRAINT FOREIGN KEY(yearId) REFERENCES Years(yearId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(monthId) REFERENCES Months(monthId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(varietyId) REFERENCES Variety(varietyId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE MinorPaddy(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    yearId INT,
    monthId INT,
    varietyId INT,
    monthlyProgress FLOAT,
    CONSTRAINT FOREIGN KEY(yearId) REFERENCES Years(yearId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(monthId) REFERENCES Months(monthId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(varietyId) REFERENCES Variety(varietyId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE RainfedPaddy(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    yearId INT,
    monthId INT,
    varietyId INT,
    monthlyProgress FLOAT,
    CONSTRAINT FOREIGN KEY(yearId) REFERENCES Years(yearId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(monthId) REFERENCES Months(monthId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(varietyId) REFERENCES Variety(varietyId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);