CREATE TABLE ADMIN(
    nic VARCHAR(20) PRIMARY KEY,
    username VARCHAR(20),
    password VARCHAR(50)
);

INSERT INTO ADMIN VALUES("98737397923","admin","admin");


CREATE TABLE ADA_ZONE(
    adaId VARCHAR(50) PRIMARY KEY,
    adaName VARCHAR(50)
);

CREATE TABLE DISTRICT(
    districtId VARCHAR(50) PRIMARY KEY,
    adaId VARCHAR(50),
    districtName VARCHAR(50),
    CONSTRAINT FOREIGN KEY(adaId) REFERENCES ADA_ZONE(adaId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE DS(
    dsId VARCHAR(50) PRIMARY KEY,
    districtId VARCHAR(50),
    dsName VARCHAR(50),
    CONSTRAINT FOREIGN KEY(districtId) REFERENCES DISTRICT(districtId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE ASCenter(
    ascId VARCHAR(50) PRIMARY KEY,
    dsId VARCHAR(50),
    ascName VARCHAR(50),
    CONSTRAINT FOREIGN KEY(dsId) REFERENCES DS(dsId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE AI_RANGE(
    rangeId VARCHAR(50) PRIMARY KEY,
    ascId VARCHAR(50),
    rangeName VARCHAR(50),
    CONSTRAINT FOREIGN KEY(ascId) REFERENCES ASCenter(ascId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);

CREATE TABLE AI_list(
    Num INT AUTO_INCREMENT UNIQUE,
    ADA_Zone VARCHAR(50),
    DISTRICT VARCHAR(50),
    DS VARCHAR(50),
    CENTER VARCHAR(50),
    AI_range VARCHAR(50),
    AI_name VARCHAR(100),
    NIC VARCHAR(20) PRIMARY KEY,
    Telephone_no VARCHAR(20),
    EMAIL VARCHAR(50),
    adaId VARCHAR(50),
    districtId VARCHAR(50),
    dsId VARCHAR(50),
    ascId VARCHAR(50),
    rangeId VARCHAR(50),
    CONSTRAINT FOREIGN KEY(adaId) REFERENCES ADA_ZONE(adaId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(districtId) REFERENCES DISTRICT(districtId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(dsId) REFERENCES DS(dsId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(ascId) REFERENCES ASCenter(ascId)
    ON  DELETE CASCADE ON  UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY(rangeId) REFERENCES AI_RANGE(rangeId)
    ON  DELETE CASCADE ON  UPDATE CASCADE
);
